### ISSUE TITLE
Travis builds/tests are failing

### ISSUE THREAD

**Issue by joelpurra** [getdnsapi/getdns-node#7]
Building and testing on Travis hasn't worked properly [since June 2015](https://travis-ci.org/getdnsapi/getdns-node/builds).

- The current issues seems to stem from `This version of node/NAN/v8 requires a C++11 compiler` during compilation for [`iojs v3`](https://travis-ci.org/getdnsapi/getdns-node/jobs/147653625) and most likely major `node` versions higher than `v0.12` (untested). It's just a [configuration](https://github.com/netiam/experiments/blob/master/.travis.yml) [issue](https://github.com/travis-ci/travis-ci/issues/4771).
- For `node` [`v0.10`](https://travis-ci.org/getdnsapi/getdns-node/jobs/147653623) and [`v0.12`](https://travis-ci.org/getdnsapi/getdns-node/jobs/147653624) one test seems to be failing (see below). Could it be a timeout?

```text
  1) getdns test TLSHostname TLS hostname validation should return successfully:
     Error: expected { msg: 'Error issuing query', code: 1 } to be falsy
      at Assertion.assert (node_modules/expect.js/index.js:96:13)
      at Assertion.ok (node_modules/expect.js/index.js:115:10)
      at Function.ok (node_modules/expect.js/index.js:499:17)
      at test/test.js:321:39
      at Context.ctx.general (getdns.js:50:27)
      at Context.<anonymous> (test/test.js:320:13)
```

**Comment by joelpurra** [comment]
With tests passing locally since #6 and on Travis (for node 4, 5, 6) since #12, I'm closing this.
